### ISSUE TITLE
Question: Can we change the layout?

### ISSUE THREAD

**Issue by sali1982** [rjsf-team/react-jsonschema-form#1551]
How we can specify the location of fields? 
I want 2 of my forms be side by side for example?
Or I want my title be next to the textbox not on top of it.
Or I need one textbox small one big
Are these doable? example?

**Comment by epicfaace** [comment]
You will need to use `classNames` on the uiSchema and then style those class names using CSS>

**Comment by Viswanathan24** [comment]
Please provide any examples of changing the layout of the form.

**Comment by andraz** [comment]
I used `classNames` with this and it worked great.

```scss
.w100p {
  width: 96%;
  margin: 0.6em 2%;
  display: inline-block;
}

.w50p {
  width: 46%;
  margin: 0.6em 2%;
  display: inline-block;
}

.w33p {
  width: 29.3%;
  margin: 0.6em 2%;
  display: inline-block;
}
```
