### ISSUE TITLE
Browser element ID collision: Found 2 elements with non-unique id

### ISSUE THREAD

**Issue by Morriz** [rjsf-team/react-jsonschema-form#1933]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

No snippet given. It is not needed for the below observation.

### Description

The ultimately horrible idea of generating elements ids which are not unique, has led to the case of, well, you guessed it: id collission:
```
[DOM] Found 2 elements with non-unique id #root_type: (More info: https://goo.gl/9p2vKq) <input type=​"hidden" id=​"root_type" value=​"docker-registry">​ <input type=​"hidden" id=​"root_type" value=​"docker-registry">​ 
```
We are hiding an input that is used behind the scenes to capture the input of oneOf.

Anyway, I will create another issue with the request to get rid of html element id usage. The element generation logic should  instead create valid html selectors. Please follow best practices when it comes to frontend development.

### Version

2.1.0

**Comment by Morriz** [comment]
Example config used:
```yaml
Secret:
  type: object
  properties:
    name:
      type: string
    type:
      type: string
      default: docker-registry
  oneOf:
    - title: docker-registry
      properties:
        type:
          type: string
          enum: [docker-registry]
          default: docker-registry
    - title: generic
      properties:
        type:
          type: string
          enum: [generic]
          default: generic
  required: [name, type]
  default: docker-registry
```
```js
{ type: { 'ui:widget': 'hidden' } }
```
